# Generated by Django 4.2.1 on 2023-05-06 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='citybook.category', verbose_name='Категория')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='citybook.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведении',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Почта')),
                ('additional_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Доп.номер телефона')),
                ('work_schedule', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Режим работы')),
                ('img', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фотография')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='citybook.place')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
